# Generated by Django 3.1.4 on 2020-12-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidadAcademica', '0002_auto_20201203_2305'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersrole',
            name='unidad_academica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidadAcademica.unidadacademica'),
        ),
    ]
