# Generated by Django 3.1.4 on 2020-12-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersrole_unidad_academica'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersrole',
            name='disponible',
            field=models.BooleanField(default=0),
        ),
    ]
