# Generated by Django 3.1.4 on 2020-12-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersrole_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersrole',
            name='evaluador',
            field=models.CharField(blank=True, choices=[('originalidad', 'Originalidad'), ('estilos', 'Estilos'), ('pedagogo', 'Pedagogo'), ('comunicologo', 'Comunicologo'), ('ninguno', 'Ninguno')], default='ninguno', max_length=12, null=True),
        ),
    ]
