# Generated by Django 3.1.4 on 2020-12-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.CharField(blank=True, choices=[('NS', 'Nivel Superior'), ('NMS', 'Nivel Medio Superior')], default='NMS', max_length=3, null=True)),
                ('id_escuela', models.CharField(max_length=128)),
            ],
        ),
    ]
