# Generated by Django 3.1.4 on 2020-12-04 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unidadAcademica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadacademica',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadacademica',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
