# Generated by Django 3.1.4 on 2020-12-10 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio', models.IntegerField()),
                ('id_upev', models.IntegerField()),
                ('usuario_plataforma', models.CharField(max_length=70)),
                ('password_plataforma', models.CharField(max_length=70)),
                ('revision', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(blank=True, choices=[('Originalidad', 'Originalidad'), ('Estilos', 'Estilos'), ('Diseño', 'Diseño'), ('Proceso', 'Proceso'), ('Terminado', 'Terminado')], default='-', max_length=20, null=True)),
                ('terminado', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('materia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materias.materia')),
            ],
        ),
    ]
