# Generated by Django 3.1.4 on 2020-12-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etp',
            name='solicitud_aprobada',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
