# Generated by Django 3.1.4 on 2020-12-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etps', '0002_etp_solicitud_aprobada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etp',
            name='estado',
            field=models.CharField(blank=True, choices=[('Originalidad', 'Originalidad'), ('Estilos', 'Estilos'), ('Diseño', 'Diseño'), ('Proceso', 'Proceso'), ('Terminado', 'Terminado')], default='Proceso', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etp',
            name='id_upev',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etp',
            name='revision',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etp',
            name='solicitud_aprobada',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='etp',
            name='terminado',
            field=models.BooleanField(default=0),
        ),
    ]
