# Generated by Django 3.1.4 on 2020-12-18 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etps', '0003_auto_20201216_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='etp',
            name='solicitante',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
