# Generated by Django 3.1.4 on 2020-12-18 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etps', '0004_etp_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etp',
            name='solicitante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
