# Generated by Django 3.1.4 on 2020-12-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etps', '0007_auto_20201218_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etp',
            name='estado',
            field=models.CharField(blank=True, choices=[('Originalidad', 'Originalidad'), ('Estilos', 'Estilos'), ('Diseño', 'Diseño'), ('Proceso', 'Proceso'), ('Espera', 'Espera'), ('Terminado', 'Terminado')], default='Proceso', max_length=20, null=True),
        ),
    ]
