# Generated by Django 3.1.4 on 2020-12-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etps', '0008_auto_20201226_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etp',
            name='estado',
            field=models.CharField(blank=True, choices=[('Originalidad', 'Originalidad'), ('Pedagógico', 'Pedagógico'), ('Comunicación', 'Comunicación'), ('Estilos', 'Estilos'), ('Técnicos', 'Técnicos'), ('Proceso', 'Proceso'), ('Espera', 'Espera'), ('Terminado', 'Terminado')], default='Proceso', max_length=20, null=True),
        ),
    ]
