# Generated by Django 3.1.4 on 2021-01-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etps', '0010_etp_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etp',
            name='documento',
            field=models.FileField(upload_to='solicitudes/etp/'),
        ),
    ]
