# Generated by Django 3.1.4 on 2021-01-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etps', '0011_auto_20210113_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='etp',
            name='pendientes',
            field=models.BooleanField(default=0),
        ),
    ]
