# Generated by Django 3.1.4 on 2021-01-15 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etps', '0011_auto_20210113_0326'),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='etp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etps.etp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='evaluador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
