# Generated by Django 3.1.4 on 2021-01-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20210114_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='etp',
            new_name='etp_id',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='evaluador',
            new_name='evaluador_id',
        ),
    ]
