# Generated by Django 3.1.4 on 2021-01-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_auto_20210114_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='etp_id',
            new_name='etp',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='evaluador_id',
            new_name='evaluador',
        ),
    ]
