# Generated by Django 3.1.4 on 2021-01-16 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0005_comentario_revisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='eptEstado',
            field=models.CharField(default='Originalidad', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
