# Generated by Django 3.1.4 on 2020-12-26 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_usersrole_evaluador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_tarea', models.CharField(blank=True, choices=[('Pendientes', 'Pendientes'), ('Haciendo', 'Haciendo'), ('Espera', 'Espera'), ('Hecho', 'Hecho')], default='Pendientes', max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersrole')),
            ],
        ),
    ]
