# Generated by Django 3.1.4 on 2020-12-26 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etps', '0007_auto_20201218_1553'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='etp_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etps.etp'),
            preserve_default=False,
        ),
    ]
