# Generated by Django 3.1.4 on 2020-12-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_auto_20201222_2033'),
        ('tareas', '0002_tarea_etp_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='equipo_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo'),
            preserve_default=False,
        ),
    ]
