# Generated by Django 3.1.4 on 2020-12-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_tarea_equipo_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='equipo_task',
        ),
    ]
