# Generated by Django 3.1.4 on 2020-12-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipo', models.CharField(max_length=50)),
                ('evaluador_originalidad', models.CharField(max_length=50)),
                ('evaluador_estilos', models.CharField(max_length=50)),
                ('evaluador_diseno', models.CharField(max_length=50)),
                ('evaluador_proceso', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id_etp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etps.etp')),
            ],
        ),
    ]
