# Generated by Django 3.1.4 on 2020-12-23 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='evaluador_diseno',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='evaluador_proceso',
        ),
        migrations.AddField(
            model_name='equipo',
            name='evaluador_comunicologo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proceso', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='evaluador_pedagogo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diseno', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='evaluador_estilos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estilos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='evaluador_originalidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='originalidad', to=settings.AUTH_USER_MODEL),
        ),
    ]
