# Generated by Django 3.1.4 on 2021-01-14 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipos', '0003_auto_20210113_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='id_equipo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='evaluador_comunicologo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='evaluador_comunicologo',
            field=models.ManyToManyField(related_name='proceso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='evaluador_estilos',
        ),
        migrations.AddField(
            model_name='equipo',
            name='evaluador_estilos',
            field=models.ManyToManyField(related_name='estilos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='evaluador_originalidad',
        ),
        migrations.AddField(
            model_name='equipo',
            name='evaluador_originalidad',
            field=models.ManyToManyField(related_name='originalidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='evaluador_pedagogo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='evaluador_pedagogo',
            field=models.ManyToManyField(related_name='diseno', to=settings.AUTH_USER_MODEL),
        ),
    ]
