# Generated by Django 3.1.4 on 2021-01-14 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipos', '0004_auto_20210113_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='evaluador_comunicologo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='evaluador_comunicologo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='proceso', to='auth.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='evaluador_estilos',
        ),
        migrations.AddField(
            model_name='equipo',
            name='evaluador_estilos',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estilos', to='auth.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='evaluador_originalidad',
        ),
        migrations.AddField(
            model_name='equipo',
            name='evaluador_originalidad',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='originalidad', to='auth.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='evaluador_pedagogo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='evaluador_pedagogo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='diseno', to='auth.user'),
            preserve_default=False,
        ),
    ]
