# Generated by Django 3.1.4 on 2020-12-10 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidadAcademica', '0002_auto_20201203_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, choices=[('FM', 'FM'), ('MB', 'MB'), ('CS', 'CS'), ('OT', 'OT')], default='-', max_length=3, null=True)),
                ('id_carrera', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('unidadacademica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidadAcademica.unidadacademica')),
            ],
        ),
    ]
